sudo: false
language: node_js
node_js:
- 9.3.0
os:
- osx
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- npm install
script:
- travis_wait 30 npm test
after_success:
- npm run semantic-release
env:
  global:
  - secure: im3vniEtFXLCwRqWRryeLvn0ToOPGu01CtEYLyREFcQ5ZIe6EPAasSwh3byxlW97g33ccu+M07YFCc6Ohup8LkM3SLExn87g/Y4sFOBBLU1WNeFHnslol4jc9WI5ClvP9EICVzZL5NlZA5hyfp6T5CH4nSzNfoQTeskTaayzA45TJGSQSj6qRdBuPMXKPQQtT3HZtu/Afv82n2S5UUQIXGd9dQpqz3e4/PKEnlH9k4xkj3FkXXAMHAVrnZRErmLOhdfCyMki1XAIgbKV46tecrDMFSs6RN2FtSkWagPjkkOEN1pVxQEHmMUoq893XLDRATd054wjmXOFGnv2HUH18CUUdHVGhLPaleBIBeQkIjuLkExv9wz9INTraK7hIKFabSxRRraH2mV3fBhyhMER4GnGxEnc1U3XuG68Jio0sPmrFaeI3PSH20R0fKgBDIlFC5Bvw4e8VSjglPfTMyAGzkgfdlCzHodfQ19mqJpR2CofK1HtS8hUD8K7Uv5fSCaXWZXAwqE52J2ic9en7Dhe8qUSzT8FlVedk9vuAkI0gVqLIK7Mn2U1nx8yQNpUPkqlTgBPCr9v9Eq5RS5pn6LmkyDcXhNJkZDTTxtLh5weoVcONdM6boYHfTIE525mqDO1xJYpmW08LFW2SHbnjohV+ipSg0vqlUeQnebBRV9DoP8=
  - secure: f2cb7ZmnCKxT1F8xSylzRhV79bVQP532Fcqu787gaXLisqWC/Q9vcnwbt+Qtv1aFGuwuZhIBBG32rnbMZAcHVcu2JBjufVbFz4S68oPsCCg6r54bonYOliIvmaPo556A9RMZxuzhsS0YiAW1oNUznH4AZvirdlx5AZQiSNnMzqAkmhzZrlsf6BcqtARgfsAWRM3HJrYruxqvBdz+n7h9jHk20KEcNLDZkuBMm7NSMEx/zjDMFkM7q0qocwC5SGSbT/3tFtozSjpw4VxXgd84xvzdY9qwjqX7tydkvLPK+zTBUicI4S8kw+S3DAJpSBfSok7E5fcC/ptGU3JiLApY26Kzz9PgrX0vebKgnGjr+jjSz2QvNDPPd8QMf3J7eRaqDaUGMMZjCwiXcCF4zDGsYx4xBZOKOPVCAJ36ma1Ny1Yivgc7gygPEfFcRhMc5V2aVlJWsu4WsvvmxKY+HI9iT+WgdmE/pXkm3ffWlqrrqVdFyDIXk+TVbfH1wb9IMGX2tUG0baGJb5y9ruUQKnVf0ydCAw8KETTpD99iuxwDAYjoMXw83PER74Yf8L54QqVXOc2zqCjtF8FLNeSd8pbuVKIvsEIHxKPZ+zDNQEV91VOxpkv+utGM3TAkZLIKypvFL+1M7hD+rpalZgxGgmBgW63jpF3qjumxaM/aMdRpZYY=
